- name: Deploy webirc
  git: clone=yes repo=https://github.com/BronyTV/BTV-IRC.git dest=/home/{{ webirc_user }}/webirc
  become_user: "{{ webirc_user }}"
  become: yes
- name: Ensure git-crypt is installed
  apt: name=git-crypt state=present
- name: Install npm
  apt: name=npm state=present
- name: Install KiwiIRC
  npm: path=/home/{{ webirc_user }}/webirc
- name: Copy configuration file
  copy: src=config.js dest=/home/{{ webirc_user }}/webirc/config.js owner={{ webirc_user }} group={{ webirc_user }} mode=0660
- name: Build KiwiIRC
  command: ./kiwi build
  args:
    chdir: /home/{{ webirc_user }}/webirc/
- name: Stop any old instances
  command: ./kiwi stop
  args:
    chdir: /home/{{ webirc_user }}/webirc/
- name: Start KiwiIRC
  command: ./kiwi start
  args:
    chdir: /home/{{ webirc_user }}/webirc/
