- name: Clone repository
  git: clone=yes repo=https://github.com/BronyTV/Static-The-Discord-Bot.git dest=/home/static/Static-The-Discord-Bot
  become_user: static

- name: Install required PIP packages
  pip:
    requirements: /home/static/Static-The-Discord-Bot/requirements.txt
    state: latest
    binary: /usr/bin/pip3

- name: Restart discord bot
  service: name=discordstaticbot state=restarted enabled=yes
